#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('simple-uci').cursor()

-- Create UCI configuration file if not present
os.execute("touch /etc/config/ffmuc")

-- Delete old additional ssid
uci:delete('wireless', 'dep_radio0');

-- Get/initialize enabled state
if not uci:get('ffmuc', 'eol_ssid') then
        uci:section('ffmuc', 'eol_ssid', 'eol_ssid', {
                enabled = true
        })
        uci:save('ffmuc')
end
local enabled = uci:get_bool('ffmuc', 'eol_ssid', 'enabled')

-- Change client radio ssid
if enabled then
        uci:set('wireless', 'client_radio0', 'ssid', 'bitte-router-erneuern.ffmuc.net')
end

uci:save('wireless')

