#!/usr/bin/lua

local uci = require('simple-uci').cursor()

-- Create UCI configuration file if not present
os.execute("touch /etc/config/ffmuc")

-- Create UCI section
if uci:get("ffmuc", "geolocator", "enabled") == nil then
	uci:section('ffmuc', 'geolocator', 'geolocator', {
		enabled = '0',
		update_interval = '10',
		min_distance = '250',
		min_accuracy = '150',
	})
	uci:commit("ffmuc")
end

if not uci:get_bool("ffmuc", "geolocator", "enabled") then
	return
end

-- Execute locator every 10 minutes
local f = io.open("/usr/lib/micron.d/ffmuc-geolocator", 'w')
f:write("*/10 * * * *  /usr/bin/ffmuc-geolocate --cron\n")
f:close()
