#!/usr/bin/lua

local sys_stat = require 'posix.sys.stat'
local pio = require 'posix.stdio'
local uci = require("simple-uci").cursor()

local file = '/etc/config/currentsite'

if not uci:get('gluon', 'core') then
	uci:section('gluon', 'core', 'core')
end
if uci:get('gluon', 'system') then
	uci:delete('gluon', 'system')
end
if sys_stat.stat(file) then
	local domain = uci:get('currentsite', 'current', 'name')
	uci:set('gluon', 'core', 'domain', domain)
	os.remove(file)
end

uci:save('gluon')

-- exclude file from persisting during sysupgrade if exist
local sysfile = "/etc/sysupgrade.conf"
local tmpsysfile = "/tmp/sysupgrade.conf"
local exist = false

if not sys_stat.stat(sysfile) then
    -- abort script as we do not need to remove sth. in an not-existent file
    os.exit()
end

local fout = io.open(tmpsysfile,"a")

for line in io.lines(sysfile) do
	if line == file then
		exist = true
	else
		fout:write(line .. "\n")
	end
end
fout:close()

if exist then
	os.remove(sysfile)
	pio.rename(tmpsysfile, sysfile)
else
	os.remove(tmpsysfile)
end