#!/usr/bin/lua

local fs = require 'nixio.fs'
local uci = require("simple-uci").cursor()

local file = '/etc/config/currentsite'

if not uci:get('gluon', 'core') then
	uci:section('gluon', 'core', 'core')
end
if uci:get('gluon', 'system') then
	uci:delete('gluon', 'system')
end
if fs.stat(file) then
	local domain = uci:get('currentsite', 'current', 'name')
	uci:set('gluon', 'core', 'domain', domain)
	fs.remove(file)
end

uci:save('gluon')

-- exclude file from persisting during sysupgrade if exist
local sysfile = "/etc/sysupgrade.conf"
local tmpsysfile = "/tmp/sysupgrade.conf"
local exist = false

local fout = io.open(tmpsysfile,"a")

for line in io.lines(sysfile) do
	if line == file then
		exist = true
	else
		fout:write(line .. "\n")
	end
end
fout:close()

if exist then
	fs.remove(sysfile)
	fs.move(tmpsysfile, sysfile)
else
	fs.remove(tmpsysfile)
end